steps:
  - name: gcr.io/cloud-builders/mvn
    entrypoint: bash
    args: ['--version']

  - name: gcr.io/cloud-builders/mvn
    entrypoint: bash
    args: ['cd backend', 'test']

  - name: maven:3-openjdk-15
    entrypoint: mvn
    args: ['package', '-Dmaven.test.skip=true']

  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: ['-c', 'build', '-t', 'gcr.io/capstone-teddys-corona-diaries/corona-diaries', '--build-arg=JAR_FILE=target/teddys-corona-diaries', '.']



